#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Civil News Hub - 정적 데이터 번들 자동 생성기 (build_data_bundle.py)
---------------------------------------------------------------------
크롤링된 실제 데이터(news.json, contests.json, jobs.json, jbnu_albas.json, swuniv_programs.json)를
정적 JavaScript 번들(static/cnh_data_bundle.js)로 컴파일합니다.

[도입 목적 및 효과]:
1. file:/// 프로토콜(브라우저에서 HTML 직접 더블클릭) 시 브라우저 CORS 차단 에러를 100% 회피.
2. 로컬 웹 서버(app.py)가 꺼져있거나 오프라인 상태여도 실제 데이터가 0.001초 만에 즉시 렌더링.
3. 소스코드 내 '가짜 예시 데이터(더미)' 노출 사고를 원천 차단.
"""

import os
import json

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = os.path.join(BASE_DIR, "data")
STATIC_DIR = os.path.join(BASE_DIR, "static")
OUTPUT_BUNDLE_PATH = os.path.join(STATIC_DIR, "cnh_data_bundle.js")

def build_bundle():
    print("[*] Civil News Hub 데이터 번들 컴파일 시작...")
    os.makedirs(STATIC_DIR, exist_ok=True)

    files_map = {
        "news": os.path.join(DATA_DIR, "news.json"),
        "contests": os.path.join(DATA_DIR, "contests.json"),
        "jobs": os.path.join(DATA_DIR, "jobs.json"),
        "albas": os.path.join(DATA_DIR, "jbnu_albas.json"),
        "swuniv": os.path.join(DATA_DIR, "swuniv_programs.json"),
    }

    bundle_data = {}
    stats = {}

    for key, path in files_map.items():
        if os.path.exists(path):
            try:
                with open(path, "r", encoding="utf-8") as f:
                    data = json.load(f)
                    bundle_data[key] = data
                    items = data.get("articles") or data.get("contests") or data.get("jobs") or data.get("programs") or []
                    stats[key] = len(items)
            except Exception as e:
                print(f"⚠️ [{key}] JSON 로드 실패 ({e}), 빈 데이터 할당")
                bundle_data[key] = {}
                stats[key] = 0
        else:
            print(f"⚠️ [{key}] 파일 미발견: {path}")
            bundle_data[key] = {}
            stats[key] = 0

    js_content = (
        "// Civil News Hub: Real Live Data Bundle (Auto-generated by build_data_bundle.py)\n"
        "// DO NOT EDIT DIRECTLY. Run `python build_data_bundle.py` to re-generate.\n"
        f"window.CNH_STATIC_DATA = {json.dumps(bundle_data, ensure_ascii=False, separators=(',', ':'))};\n"
    )

    with open(OUTPUT_BUNDLE_PATH, "w", encoding="utf-8") as f:
        f.write(js_content)

    file_size_kb = len(js_content.encode("utf-8")) / 1024
    print(f"✅ 번들 생성 완료: {OUTPUT_BUNDLE_PATH} ({file_size_kb:.1f} KB)")
    print(f"   - 뉴스: {stats.get('news', 0)}건")
    print(f"   - 공모전: {stats.get('contests', 0)}건")
    print(f"   - 채용: {stats.get('jobs', 0)}건")
    print(f"   - 전북대 알바: {stats.get('albas', 0)}건")
    print(f"   - SW 프로그램: {stats.get('swuniv', 0)}건")

if __name__ == "__main__":
    build_bundle()
